apiVersion: v1

kind: Service
metadata:
  name: demo-posts-service
spec:
  type: NodePort
  selector: 
    app: demo-posts
  ports: 
    - name: demo-posts
      protocol: TCP
      port: 4000 # The node port, port coming in our nodeport
      targetPort: 4000 # port for app listening on our traffic