apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-client-deployment
spec:
  replicas: 1

  # Section that defines the app lable
  # as key value store ['app' : demo-posts]
  selector:
    matchLabels:
      app: demo-client

  # This parts defines that the deployment should create pods
  # for label ['app': demo-posts]
  template:
    metadata:
      labels:
        app: demo-client
    spec: 
      containers:
        - name: demo-client
          image: muazwazir1/client-demo:latest

---

apiVersion: v1
kind: Service
metadata: 
  name: client-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: demo-client
  ports:
    - name: demo-client
      protocol: TCP
      port: 3000
      targetPort: 3000